Repository alentar/rpms-server, pull requests merged in 2018-03, with the labels that each got.

#1 Added more roles
  README.md
  src/models/user.model.js
Labels: enhancement

#6 Enhancement/gulp user
  README.md
  apidoc.json
  gulpfile.js
  package.json
  src/controllers/auth.controller.js
  src/models/user.model.js
  src/routes/api/auth.route.js
  src/routes/api/index.js
  src/services/express.js
  src/validations/user.validation.js
  yarn.lock
Labels: enhancement

#13 Feature/wizard
  bin/wizard.js
  package.json
  src/models/user.model.js
  src/validations/user.validation.js
  yarn.lock
Labels: feature

#14 Fix/token
  src/controllers/auth.controller.js
  src/routes/api/auth.route.js
Labels: enhancement

#19 Feature : Users
  docs/docs/api_data.js
  docs/docs/api_data.json
  docs/docs/api_project.js
  docs/docs/api_project.json
  gulpfile.js
  package.json
  src/controllers/auth.controller.js
  src/controllers/user.controller.js
  src/models/user.model.js
  src/routes/api/auth.route.js
  src/routes/api/index.js
  src/routes/api/user.route.js
  src/validations/user.validation.js
  yarn.lock
Labels: enhancement, feature

#27 Fix/users
  bin/wizard.js
  src/models/user.model.js
  src/validations/user.validation.js
Labels: feature

#29 allow to get all users
  src/models/user.model.js
Labels: bug

#30 Fix/users
  src/controllers/user.controller.js
  src/models/user.model.js
  src/validations/user.validation.js
Labels: bug

#33 Title Case name field
  src/controllers/user.controller.js
Labels: enhancement

#36 Travis with gulp linting
  .travis.yml
Labels: enhancement

#35 Titlecase namefield enforce
  src/controllers/user.controller.js
Labels: enhancement

#37 Feature/wards beds devices
  docs/docs/api_data.js
  docs/docs/api_data.json
  docs/docs/api_project.js
  docs/docs/api_project.json
  src/controllers/bed.controller.js
  src/controllers/user.controller.js
  src/controllers/ward.controller.js
  src/models/bed.model.js
  src/models/device.model.js
  src/models/refreshToken.model.js
  src/models/ward.model.js
  src/routes/api/auth/index.js
  src/routes/api/index.js
  src/routes/api/user/index.js
  src/routes/api/ward/beds/index.js
  src/routes/api/ward/index.js
  src/validations/bed.validation.js
  src/validations/ward.validation.js
Labels: enhancement, feature, missing documentation

#39 remove comment
  src/controllers/bed.controller.js
Labels: bug

#42 Feature/device provision
  src/controllers/bed.controller.js
  src/controllers/device.controller.js
  src/controllers/user.controller.js
  src/controllers/ward.controller.js
  src/middlewares/error-handler.js
  src/models/device.model.js
  src/models/user.model.js
  src/models/ward.model.js
  src/routes/api/device/index.js
  src/routes/api/index.js
  src/services/express.js
  src/utils/DeviceError.js
  src/validations/bed.validation.js
  src/validations/device.validation.js
Labels: enhancement, feature

#44 Bulk create for beds
  src/controllers/bed.controller.js
  src/routes/api/ward/beds/index.js
  src/validations/bed.validation.js
Labels: enhancement

#45 removed console log
  src/controllers/bed.controller.js
Labels: bug

#46 add device id to auth
  src/controllers/device.controller.js
Labels: feature

#47 Fix/typo
  .gitignore
  src/controllers/ward.controller.js
Labels: bug
